public  class checkdatatype2 {
    public void methodBoolean(){
        Boolean checkBoolean = true;
       system.debug(checkBoolean);
       }
   
   
       public void methodInteger(){
   
       integer varfirst = 1;
       integer varsecond = 2;
   
       system.debug(varfirst);
       system.debug(varsecond);
       
   
       }
   
       public void stringMethod(){
   
       string varname = 'Name';
       string var2name = 'Madina';
       system.debug(varname);
       system.debug(var2name);
       
   
       }
}
