public  class PrimitiveDataTypeDemo1 {
    public void print1() {
        ID  id1 = '0038Z00002tER8SQAW';
        system.debug('print id =' + id1);

        Object obj1 = 'This is a string';
        Object obj2 = 15;
        Object obj3 = '0038Z00002tER8SQAW';
        Object obj4 = true;

        system.debug('obj1 = ' + obj1);
        system.debug('obj2 = ' + obj2);
        system.debug('obj3 = ' + obj3);
        system.debug('obj4 = ' + obj4);

    }
}
