public class PrimitiveDataTypeDemo {
    public void printBasicDataType(){
        string batchName = 'Falcons 8';
        integer totalCandidates = 40;
        boolean isAdminCompleted = true;

        system.debug(batchName);
        system.debug(totalCandidates);
        system.debug(isAdminCompleted);

        string batchDescription = batchName + ' are the Bestest';
        system.debug(batchDescription);
    }


ID  id = '0038Z00002tER8SQAW';
    ID id2 = 'stringrecord';
    system.debug('id is' + id1);
    system.debug('id2 is' + id2);
}


